; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; 项目配置说明：
;   - 使用NodeMCU v2开发板
;   - 包含TFT显示、LVGL图形库、JSON解析和NTP客户端等依赖
;   - 设置高速串口通信(921600 baud)
;   - 启用调试构建类型

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	bodmer/TFT_eSPI@^2.5.0
	lvgl/lv_arduino@^3.0.1
	bblanchon/ArduinoJson@^6.20.0
	arduino-libraries/NTPClient @ ^3.2.1
    PaulStoffregen/Time @ ^1.6.1
monitor_speed = 921600
upload_speed = 921600
monitor_filters = esp8266_exception_decoder
build_type=debug
